version: "3.9"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nest-app
    networks:
      - app_net

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - minio
    env_file:
      - .env
    networks:
      - app_net

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app_net

volumes:
  minio_data:

networks:
  app_net: